name: Build iturbo branch of MOM6 with TIM and FMS

# See the following link for more information on the NCAR HPC development containers:
# https://hub.docker.com/u/ncarcisl

on:
  workflow_dispatch:
  push:
    branches: ["main", "ci-tests", "container-ci"]
  pull_request:
    branches: ["main", "ci-tests", "container-ci"]

jobs:

  run-matrix:
    strategy:
      fail-fast: false
      matrix:
        compiler: [ oneapi, gcc14 ]
        mpi:      [ mpich ]
        gpu:      [ nogpu ]
        arch:     [ x86_64 ]
        runner:   [ ubuntu-latest, gha-runner-turbo ]

    name: Build Test
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash -elo pipefail {0}

    container:
      image: docker.io/ncarcisl/cisldev-${{ matrix.arch }}-almalinux9-${{ matrix.compiler }}-${{ matrix.mpi }}${{ matrix.gpu == 'cuda' && '-cuda' || '' }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Switch MOM6 to dev/turbo-debug
        run: |
          cd submodules/MOM6/
          git fetch origin
          git checkout --recurse-submodules dev/turbo-debug
          echo "Head of dev/turbo-debug is this commit:"
          git log -1 --decorate
          cd ../..

      - name: Interrogate Runtime Environment
        run: |
          cat /container/config_env.sh
          lscpu
          echo && echo && echo
          echo '----------------------------------------------------------------'
          echo && echo && echo
          echo "CC=${CC}"
          echo "CXX=${CXX}"
          echo "FC=${FC}"
          echo "F77=${F77}"
          echo
          echo "CFLAGS=${CFLAGS}"
          echo "CPPFLAGS=${CPPFLAGS}"
          echo "CXXFLAGS=${CXXFLAGS}"
          echo "FCFLAGS=${FCFLAGS}"
          echo "F77FLAGS=${F77FLAGS}"
          export CC CXX FC F77 CFLAGS CXXFLAGS FCFLAGS F77FLAGS CPPFLAGS
          conda --version 2>/dev/null || echo " --> no conda in this container"
          which mpicc
          mpicc --version 2>/dev/null || true

      - name: Build MOM6 with TIM
        run: |
          ./build.sh --compiler ${COMPILER_FAMILY} --machine container --infra TIM
          if [[ ! `nm --print-armap bin/${COMPILER_FAMILY}/MOM6_using_TIM/MOM6-infra/libinfra-TIM.a | grep tim_com` ]]; then
            echo "ERROR: Did not find tim_com in libinfra-TIM.a (did TIM module change name?)"
            exit 1
          fi

      - name: Build MOM6 with FMS2
        run: |
          ./build.sh --compiler ${COMPILER_FAMILY} --machine container --infra FMS2
          if [[ `nm --print-armap bin/${COMPILER_FAMILY}/MOM6_using_FMS2/MOM6-infra/libinfra-FMS2.a | grep tim_com` ]]; then
            echo "ERROR: Found tim_com in libinfra-FMS2.a (=> using TIM infra, not FMS)"
            exit 1
          fi
